import './global.css';
import Navbar from './components/Navbar';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50 min-h-screen text-gray-900">
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
